import type { ReactNode } from 'react';

export const PRICING_FEATURE_INFO: Record<string, ReactNode> = {
	'tool-calls': (
		<p>
			A tool call is a single event to a third-party API. Sending a Slack
			message, searching a Notion database, or updating a Hubspot deal are all
			tool calls. Corsair is able to offer unlimited tool calls on every tier.
			All other integration solutions cap tool calls, even on paid plans.
		</p>
	),
	connections: (
		<p>
			A connection is a single user&apos;s account on an integration. Amy&apos;s
			Gmail integration and Bob&apos;s Google Calendar integration are counted
			as two connections. On the Hobby plan, 50 connections are permitted per
			30-day period.
		</p>
	),
	webhooks: <p>A webhook is an inbound event from an external API.</p>,
	permissions: (
		<>
			<p>
				<span className="font-medium text-[#1c1c1c]">Managed auth pages</span>{' '}
				are auto-generated by Corsair so you or your users are easily able to
				sign into different integrations. For example, if an agent is asked to
				send an email in Gmail, but it isn&apos;t signed into Gmail, Corsair
				will auto-generate a sign in link that the user can go to and complete
				authentication.
			</p>
			<p>
				<span className="font-medium text-[#1c1c1c]">
					Managed permissions pages
				</span>{' '}
				are auto-generated by Corsair so specific actions require explicit
				approval. For example, if you have configured Corsair to require
				approval before creating a calendar invite, the agent will get blocked
				from creating it. A permission link will be generated and given back to
				you to approve or deny. Once approved, the agent will be allowed to
				complete that action.
			</p>
		</>
	),
	'team-members': (
		<p>
			These are the number of team members allowed to your Corsair workspace.
		</p>
	),
	'consent-screen': (
		<p>
			The managed auth and permissions pages are Corsair-branded by default. You
			can override this and add your own custom icons and naming to personalize
			the app to your own branding.
		</p>
	),
	support: (
		<p>
			The Corsair team is very responsive on Discord. If you have any issues, we
			are always available to help (whether or not you&apos;re on a paid plan).
			Pro plan users will also receive a dedicated Slack channel for priority
			support. Enterprise customers will receive founder phone numbers so we can
			be reached at any time of day.
		</p>
	),
	'custom-integrations': (
		<p>
			We are constantly adding new integrations to Corsair. Our goal is to
			support every API that exists. If you need an API that we don&apos;t have
			yet, please create a Github issue for it. The Corsair team or Corsair
			community will try to pick it up. If you are on the Pro plan, the Corsair
			team will build the integration for you.
		</p>
	),
};
